import { Recipe } from './recipe';
import { Product } from './product';

export const RECIPEDATA:Recipe[] = [{
        "id" : 1,
        "recipe" : 'Apple Pie',
        "cooking_time" : 9,
        "prep_time" : 10,
        "estimated_cost" : 55
    },
    {
        "id" : 2,
        "recipe" : 'Chicken soup',
        "cooking_time" : 55,
        "prep_time" : 20,        
        "estimated_cost" : 25
    }]

export const PRODUCTSDATA:Product[] = [{
    "id": 1,
    "name": "Nike Roshe Run Premium Holiday",
    "description": "This is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using",
    "free_shipping" : true,
    "details": "jajajajajaja",
    "features": "nejenejenej",
    "sizes": ["S", "M", "L"],
    "rating": 5,
    "price": 109.90,
    "salepercent": 25,
    "discount_price": 0,
    "on_sale": true,
    "images": ["images/products/nike.jpg", "somesrc2"],
    "brand": "images/brandlogos/nike.jpg",
    "on_stock": 25
},
{
    "id": 2,
    "name": "The best Adidas shoe in the whole world",
    "description": "det er en god sko",
    "free_shipping" : true,
    "details": "jajajajajaja",
    "features": "nejenejenej",
    "sizes": ["S", "M", "L"],
    "rating": 5,
    "price": 200.51,
    "salepercent": 25,
    "discount_price": 0,
    "on_sale": true,
    "images": ["images/products/nike.jpg", "somesrc2"],
    "brand": "images/brandlogos/nike.jpg",
    "on_stock": 50
},
{
    "id": 3,
    "name": "The best Adidas shoe in the whole world",
    "description": "det er en god sko",
    "free_shipping" : true,
    "details": "jajajajajaja",
    "features": "nejenejenej",
    "sizes": ["S", "M", "L"],
    "rating": 5,
    "price": 200.51,
    "salepercent": 25,
    "discount_price": 0,
    "on_sale": true,
    "images": ["images/products/nike.jpg", "somesrc2"],
    "brand": "images/brandlogos/nike.jpg",
    "on_stock": 50
},
{
    "id": 4,
    "name": "The best Adidas shoe in the whole world",
    "description": "det er en god sko",
    "free_shipping" : true,
    "details": "jajajajajaja",
    "features": "nejenejenej",
    "sizes": ["S", "M", "L"],
    "rating": 5,
    "price": 200.51,
    "salepercent": 25,
    "discount_price": 0,
    "on_sale": true,
    "images": ["images/products/nike.jpg", "somesrc2"],
    "brand": "images/brandlogos/nike.jpg",
    "on_stock": 50
},
{
    "id": 5,
    "name": "The best Adidas shoe in the whole world",
    "description": "det er en god sko",
    "free_shipping" : true,
    "details": "jajajajajaja",
    "features": "nejenejenej",
    "sizes": ["S", "M", "L"],
    "rating": 5,
    "price": 200.51,
    "salepercent": 25,
    "discount_price": 0,
    "on_sale": true,
    "images": ["images/products/nike.jpg", "somesrc2"],
    "brand": "images/brandlogos/nike.jpg",
    "on_stock": 50
},
{
    "id": 6,
    "name": "The best Adidas shoe in the whole world",
    "description": "det er en god sko",
    "free_shipping" : true,
    "details": "jajajajajaja",
    "features": "nejenejenej",
    "sizes": ["S", "M", "L"],
    "rating": 5,
    "price": 200.51,
    "salepercent": 25,
    "discount_price": 0,
    "on_sale": true,
    "images": ["images/products/nike.jpg", "somesrc2"],
    "brand": "images/brandlogos/nike.jpg",
    "on_stock": 50
},
{
    "id": 7,
    "name": "The best Adidas shoe in the whole world",
    "description": "det er en god sko",
    "free_shipping" : true,
    "details": "jajajajajaja",
    "features": "nejenejenej",
    "sizes": ["S", "M", "L"],
    "rating": 5,
    "price": 200.51,
    "salepercent": 25,
    "discount_price": 0,
    "on_sale": true,
    "images": ["images/products/nike.jpg", "somesrc2"],
    "brand": "images/brandlogos/nike.jpg",
    "on_stock": 50
},
{
    "id": 8,
    "name": "The best Adidas shoe in the whole world",
    "description": "det er en god sko",
    "free_shipping" : true,
    "details": "jajajajajaja",
    "features": "nejenejenej",
    "sizes": ["S", "M", "L"],
    "rating": 5,
    "price": 200.51,
    "salepercent": 25,
    "discount_price": 0,
    "on_sale": true,
    "images": ["images/products/nike.jpg", "somesrc2"],
    "brand": "images/brandlogos/nike.jpg",
    "on_stock": 50
}]